version: "3.8"
services:
  app:
    container_name: docker-react
    # restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
